version: '3.5'
services:
  postgres:
    image: postgres
    ports:
      - 5432
  app:
    build:
      context: .
      target: builder
    working_dir: /go/src/app
    command: buffalo dev
    environment:
      - GO111MODULE=on
      - ADDR=0.0.0.0
      - HOST=0.0.0.0
    volumes:
      - .:/go/src/app
      - node_modules:/go/src/app/node_modules
    ports:
      - 3000:3000
      - 35729:35729
    depends_on:
      - postgres
volumes:
  node_modules:
